config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  post '/login', to: 'home#login'
  post '/logout', to: 'home#logout'
  resources :questions
  resources :votes, only: [:create]
  resources :question_comments
  root to: "home#show"
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :order, presence: true
  validates :title, presence: true
  belongs_to :question, inverse_of: :answers
  has_many :votes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, presence: true
  has_many :answers, inverse_of: :question
  accepts_nested_attributes_for :answers
  has_many :question_comments
end

app/models/question_comment.rb
class QuestionComment < ApplicationRecord
  validates :username, presence: true
  validates :body, presence: true
  belongs_to :question
end

app/models/vote.rb
class Vote < ApplicationRecord
  validates :answer_id, presence: true
  validates :username, presence: true
  belongs_to :answer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @username = session[:username] || ""
  end

  def login
    session[:username] = login_params[:username]

    respond_to do |format|
      format.html { redirect_to "/", notice: 'Succesfully login.' }
    end
  end

  def logout
    session[:username] = ""

    respond_to do |format|
      format.html { redirect_to "/", notice: 'Succesfully logout.' }
    end
  end

  private
    def login_params
      params.require(:login).permit(:username)
    end
end

app/controllers/question_comments_controller.rb
class QuestionCommentsController < ApplicationController
  def create
    @question_comment = QuestionComment.new(question_comment_params.merge(
      question_id: params[:question_id],
      username: session[:username]
    ))

    if @question_comment.save
      ActionCable.server.broadcast "questions:#{@question_comment.question_id}:question_comments", username: @question_comment.username, body: @question_comment.body
    end
  end

  private
    def question_comment_params
      params.require(:question_comment).permit(:body)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  def index
    @questions = Question.all
  end

  # GET /questions/1
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
    3.times { @question.answers.build }
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /questions/1
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /questions/1
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(
        :title,
        :body,
        answers_attributes: [:id, :order, :title, :_destroy]
      )
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  # POST /votes
  def create
    @answer = Answer.find(params[:answer_id])
    @vote = Vote.new(answer_id: @answer.id, username: session[:username])

    if @vote.save
      ActionCable.server.broadcast "question_channel", answer_id: @vote.answer_id, votes_count: @vote.answer.votes.count
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    session[:username]
  end
end

app/helpers/question_comments_helper.rb
module QuestionCommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/show.html.erb
<br />
<br />
<br />
<br />
<br />
<br />
<br />

<div class="row">
  <% if @username.present? %>
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
      <h2 class="text-center">
        Halo <%= @username %>, Silahkan <%= link_to 'masuk', questions_path %> atau <%= link_to "Logout", "/logout", method: :post %>
      </h2>
    </div>
  <% else %>
    <div class="col-sm-5"></div>
    <div class="col-sm-4">
      <%= form_tag "/login" do %>
        <div class="row">
          <div class="form-group">
            <%= label :login, "Please input username" %>
            <%= text_field :login, :username, value: @username, class: "form-control input-lg" %>
          </div>
        </div>

        <div class="row">
          <div class="text-right">
            <%= submit_tag "login", class: "btn btn-lg btn-default" %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdRubyVote</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for(question) do |f| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <%= f.fields_for :answers do |builder| %>
    <div class="field">
      <%= builder.label :order %><br/>
      <%= builder.text_field :order %>
    </div>

    <div class="field">
      <%= builder.label :title %><br/>
      <%= builder.text_field :title %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.title %></td>
        <td><%= question.body %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @question.title %></h2>
<h5><%= @question.body %></h5>

<br />

<div class="row">
  <% @question.answers.each do |answer, idx| %>
    <div class="col-sm-4">
      <div class="card" style="width: 20rem;">
        <div class="card-block">
          <h4 class="card-title"><%= answer.title %></h4>
          <p class="card-text">
            Jumlah vote:
            <span id="answer_<%= answer.id %>_votes_count"><%= answer.votes.count %></span>
          </p>
          <%= button_to 'Vote', votes_path, params: {answer_id: answer.id}, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br />

<div class="row">
  <div data-channel="question_comments" data-question-id="<%= @question.id %>" class="card card-block bg-faded" style="height: 30rem;">
    <div class="stream" style="overflow: auto;">
      <% @question.question_comments.each do |question_comment| %>
        <%= "#{question_comment.username}: #{question_comment.body}" %><br />
      <% end %>
    </div>
    <br />
    <div class="new_question_comment">
      <div class="field">
        <%= text_field :question_comment, :body, class: "form-control input-lg" %>
      </div>
    </div>
  </div>
</div>

<br />

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>